### ISSUE TITLE
gaussian mixture model

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#102]
File: https://github.com/pymc-devs/pymc-examples/blob/main/examples/mixture_models/gaussian_mixture_model.ipynb
Reviewers:

> The sections below may still be pending. If so, the issue is still available, it simply doesn't
> have specific guidance yet. Please refer to [this overview of updates](https://github.com/pymc-devs/pymc-examples/wiki/Notebook-updates-overview)

## Known changes needed
Changes listed in this section should all be done at some point in order to get this
notebook to a "Best Practices" state. However, these are probably not enough!
Make sure to thoroughly review the notebook and search for other updates.

### General updates
*

### ArviZ related
*

## Changes for discussion
Changes listed in this section are up for discussion, these are ideas on how to improve
the notebook but may not have a clear implementation, or fix some know issue only partially.

### General updates
*

### ArviZ related
*

**Comment by drbenvincent** [comment]
This could be updated to use new `pm.Mixture`

**Comment by drbenvincent** [comment]
Any reason why the cluster means can't use `pymc.distributions.transforms.Ordered`?

**Comment by drbenvincent** [comment]
Actually, anyone mind if I update this with `pm.NormalMixture`? We can get some significant simplification of this notebook.

**Comment by OriolAbril** [comment]
That sounds amazing and things like that are the reason there is a `v4 (auto)` and a `Done` category in the [tracker project](https://github.com/pymc-devs/pymc-examples/projects/1) that are clearly separated. It wasn't the case, but this notebook might have run when changing `import pymc3` to `import pymc` and theano to aesara, but that a notebook runs on v4 doesn't mean it is updated to be _documentation_ for v4.

I am not sure how much of that was already available in latest v3 releases, but the issue is the same. A notebook is added to cover and explain a specific use case, a while later we see (or have time to implement) a way to make that case better and easier, but when the feature is added to pymc, the notebook is not updated. When that happens many users won't be aware the new feature exists, and others might now but be unable to use it without an example notebook so the new feature ends up being underused and the old but well documented way of doing things prevails.

**Comment by drbenvincent** [comment]
Great. Will put in a PR soon.

**Comment by drbenvincent** [comment]
Moving this in the notebook state tracker from 'todo' to 'done'. And closing issue
