### ISSUE TITLE
api quickstart

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#107]
File: https://github.com/pymc-devs/pymc-examples/blob/main/examples/pymc3_howto/api_quickstart.ipynb
Reviewers:

> The sections below may still be pending. If so, the issue is still available, it simply doesn't
> have specific guidance yet. Please refer to [this overview of updates](https://github.com/pymc-devs/pymc-examples/wiki/Notebook-updates-overview)

## Known changes needed
Changes listed in this section should all be done at some point in order to get this
notebook to a "Best Practices" state. However, these are probably not enough!
Make sure to thoroughly review the notebook and search for other updates.

### General updates
* Remove the ignore warnings
* Add also an explanation on dims right below where `shape` is explained.
* Look for places where add links to further reference pages. There are places where we could link to profiling notebook, to posteior predictive one... and help users navigate through the notebooks.

### ArviZ related
* I think we should include a note on model comparison with loo/waic and how converting to inferencedata by default computes and stores pointwise log likelihood values. If memory constrained or not aiming for model comparison, it can be disabled with `idata_kwargs={"log_likelihood": True}` in `pm.sample` call.
* ArviZ usage is already good, but also some notes on the relation between projects, on the `pm.plot_xyz` aliases and some links to ArviZ would be nice

### Exotic dependencies
None

### Computing requirements
Models sample in <10 seconds

**Comment by farhanreynaldo** [comment]
Hi , @OriolAbril. I would like to work on this issue, is it available for PR?

**Comment by OriolAbril** [comment]
Hi, sorry for the late reply, it is available but being a high impact notebook, it will probably have timing constraints to update it along with our upcoming 4.beta version. This means we might ask for faster updates and changes and/or take over and finish the update ourselves. Let me know if this sounds ok or you'd prefer to work at your own pace on a different notebook

**Comment by farhanreynaldo** [comment]
> Hi, sorry for the late reply, it is available but being a high impact notebook, it will probably have timing constraints to update it along with our upcoming 4.beta version. This means we might ask for faster updates and changes and/or take over and finish the update ourselves. Let me know if this sounds ok or you'd prefer to work at your own pace on a different notebook

That's understandable, I think I would like to work on a different notebook at my own pace.

**Comment by cluhmann** [comment]
Closed by https://github.com/pymc-devs/pymc-examples/pull/364?  Sorry I forgot to associate this issue in the PR.
