### ISSUE TITLE
Overzealous black formatting on data lists

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc-examples#167]
Black makes a poor choice in formatting long arrays, for example in the disasters example:

<img width="628" alt="Screen Shot 2021-06-06 at 10 04 55 PM" src="https://user-images.githubusercontent.com/81476/120953760-520fb800-c713-11eb-9f37-6f30bb109faa.png">

If there isn't a way of making exceptions for instances like this, the data should be stored externally.

**Comment by OriolAbril** [comment]
It is possible to turn formatting off with `# fmt: on/off` the style guide has an example of this: https://github.com/pymc-devs/pymc3/wiki/PyMC3-Jupyter-Notebook-Style-Guide

**Comment by jacobtomlinson** [comment]
It looks like this might've been resolved in https://github.com/pymc-devs/pymc-examples/pull/628.

**Comment by fonnesbeck** [comment]
I don't get this behavior anymore, so it was apparently fixed somewhere!
