### ISSUE TITLE
Moderation analysis

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#170]
File: https://github.com/pymc-devs/pymc-examples/blob/main/examples/case_studies/moderation_analysis.ipynb
Reviewers: @drbenvincent 

> The sections below may still be pending. If so, the issue is still available, it simply doesn't
> have specific guidance yet. Please refer to [this overview of updates](https://github.com/pymc-devs/pymc-examples/wiki/Notebook-updates-overview)

**Comment by OriolAbril** [comment]
@drbenvincent I have tagged you to keep you up to date with the notebook when we update it to v4 at some point during the coming months, feel free to unsubscribe

**Comment by drbenvincent** [comment]
Am I right in thinking that the plan is for one large batch update of https://docs.pymc.io, rather than drip feeding various updates to the live site?

**Comment by OriolAbril** [comment]
The website is only updated with new releases, so the notebooks will be published there with https://github.com/pymc-devs/pymc3/issues/4658 which should happen in 1-2 weeks. I went over all the notebooks and merged everything even if I was the only reviewer to make sure they get in this update batch.

**Comment by drbenvincent** [comment]
This is also on my list to update to v4
