### ISSUE TITLE
Mediation analysis

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#171]
File: https://github.com/pymc-devs/pymc-examples/blob/main/examples/case_studies/mediation_analysis.ipynb
Reviewers: @drbenvincent 

> The sections below may still be pending. If so, the issue is still available, it simply doesn't
> have specific guidance yet. Please refer to [this overview of updates](https://github.com/pymc-devs/pymc-examples/wiki/Notebook-updates-overview)

**Comment by drbenvincent** [comment]
This is on my list to update to v4
