### ISSUE TITLE
Bayesian A/B testing

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#172]
File: https://github.com/pymc-devs/pymc-examples/blob/main/examples/case_studies/bayesian_ab_testing.ipynb
Reviewers: @tcuongd 

> The sections below may still be pending. If so, the issue is still available, it simply doesn't
> have specific guidance yet. Please refer to [this overview of updates](https://github.com/pymc-devs/pymc-examples/wiki/Notebook-updates-overview)

**Comment by OriolAbril** [comment]
Hi @tcuongd I have tagged you to keep you up to date for when we update the notebook to work with [PyMC3 4.0](https://github.com/pymc-devs/pymc3/wiki/Timeline) at some point during the coming months, feel free to unsubscribe if not interested.

**Comment by tcuongd** [comment]
Thank you! Definitely interested :)

**Comment by cuchoi** [comment]
@OriolAbril it seems that this issue should be moved to v4 after #351 ?

**Comment by OriolAbril** [comment]
Yep, moved it to v4 auto. It is using v4 (I can't judge if already using best practices and taking advantage of all improvements) but it is definitely not following book style so we need to keep the issue open
