### ISSUE TITLE
Remove mention of glm submodule

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc-examples#174]
E.g. http://docs.pymc.io/pymc-examples/examples/generalized_linear_models/GLM-linear.html#Estimating-the-model

glm submodule is being deprecated.

**Comment by OriolAbril** [comment]
indeed, thanks for the remainder. this had already started in https://github.com/pymc-devs/pymc-examples/issues/91. I have now also retriaged a couple notebooks to be more explicit about it so I'll close the issue

**Comment by almostmeenal** [comment]
> indeed, thanks for the remainder. this had already started in #91. I have now also retriaged a couple notebooks to be more explicit about it so I'll close the issue

hi im working on the notebook rn, hopefully should be done in a day, just wanted to ask, do we just need to update glm.ipynb or all other ones in the glm folder too?

**Comment by OriolAbril** [comment]
All those that use the glm module need to be updated, but we should do it one at a time

**Comment by almostmeenal** [comment]
> All those that use the glm module need to be updated, but we should do it one at a time

so um, before the bambi release thing, do i need to fix all the notebooks or just that one?

**Comment by chiral-carbon** [comment]
hey @almostmeenal! the nature of my outreachy project is such that I would primarily be involved in updating the example notebooks, which would be those for the glm module as well, though I'm far away from finishing any of that yet!! just wanted to put that here and obviously you can work on any of the issues in the notebooks if you wish to, but just in case you thought it might be a requirement on your part to update all of them then I think it's not, although I don't know about the bambi release. I hope I dont sound presumptuous and I also hope I didn't misread the discussion here 😳

**Comment by OriolAbril** [comment]
The release we discussed on slack is a pymc3 release which means we'll update the website, so we should avoid publishing broken notebooks to the best of our ability. 

Updating the notebooks to use bambi needs to be done but is not urgent in any sense, it is an extra step in the whole notebook update project, for now you should focus only on the `glm.ipynb` which is the one that's broken, other glm module uses can be progressively updated and published with next version.
