### ISSUE TITLE
Create notebook PR template

### ISSUE THREAD

**Issue by martinacantaro** [pymc-devs/pymc-examples#186]
Require PRs to follow the [Style Guide](https://github.com/pymc-devs/pymc3/wiki/PyMC3-Jupyter-Notebook-Style-Guide)

Require a statement detailing what the notebook adds in the context of our documentation and why it’s important.

Require checking that the content  isn’t already covered by another notebook

**Comment by OriolAbril** [comment]
The pull request template for pymc-examples is currently like this https://raw.githubusercontent.com/pymc-devs/pymc-examples/main/.github/PULL_REQUEST_TEMPLATE.md, the contributing guide is https://github.com/pymc-devs/pymc-examples/blob/main/CONTRIBUTING.md

**Comment by OriolAbril** [comment]
> Require a statement detailing what the notebook adds in the context of our documentation and why it’s important.

I would try to continue enforcing the contributing guide, and have PRs link to an issue (which could be about a missing notebook), otherwise it can be frustrating for contributors to start a notebook and submit a PR after significant work only to have it rejected
