### ISSUE TITLE
Add categories and labels to notebooks

### ISSUE THREAD

**Issue by martinacantaro** [pymc-devs/pymc-examples#188]
As per the [June 18th meeting,](https://github.com/pymc-devs/pymc/wiki/GSoD-2021-Meeting-Minutes#friday-june-18) categories will be used to label the different levels of documentation (beginner, intermediate, advanced) and tags will be used to label the topics.
This will improve searchability

**Comment by drbenvincent** [comment]
I think this issue is stale and can be closed. @OriolAbril?
