### ISSUE TITLE
cox_model.ipynb doesn't have formatting run on it (double fmt: off)

### ISSUE THREAD

**Issue by MarcoGorelli** [pymc-devs/pymc-examples#193]
**Notebook title**: cox_model.ipynb
**Notebook url**: https://github.com/pymc-devs/pymc-examples/blob/main/examples/survival_analysis/cox_model.ipynb

## Issue description

Cell 4 starts with
```
# fmt: off
```
and ends with 
```
#fmt: off
```

The latter should be 
```
# fmt: on
```

*Note that this issue tracker is about the contents in the notebooks, if
the notebook is instead triggering a bug or error in pymc3, please
report to https://github.com/pymc-devs/pymc3/issues instead*

## Expected output
If applicable, describe what should happen instead.

## Proposed solution
If applicable, explain possible solutions and workarounds.

**Comment by OriolAbril** [comment]
related to #127 (please tag both issues or only #127 in the PR)

**Comment by MarcoGorelli** [comment]
Ah, understood, thanks!

**Comment by MarcoGorelli** [comment]
no longer necessary, as `black`'s built-in notebook support runs cell-by-cell
