### ISSUE TITLE
Use sigma instead of sd

### ISSUE THREAD

**Issue by MarcoGorelli** [pymc-devs/pymc-examples#2]
e.g. `Normal('x', mu=mu, sigma=sigma)` rather than `Normal('x', mu=mu, sd=sigma)`

`sd` will (silently) continue working, see https://github.com/pymc-devs/pymc3/pull/4344

**Comment by CloudChaoszero** [comment]
Hey @MarcoGorelli, I am working on some big changes related to switching from pymc3 plots to arviz plots. 
* Being said, I can take this on as well, and work on both of them.

**Comment by twiecki** [comment]
That's great @CloudChaoszero - much appreciated!

**Comment by CloudChaoszero** [comment]
I updated the PR to include replacing `sd` with `sigma` parameter. 
* If any lingering ones exist, we can update it over time, I imagine.

**Comment by CloudChaoszero** [comment]
I think this Issue can be closed now. 🤞
