### ISSUE TITLE
Standardize format for references and quotations

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#203]
With myst we could now use https://sphinxcontrib-bibtex.readthedocs.io/en/latest/index.html like jupyterbook uses. It allows a centralized bibtex file with all the references with rendered bibliography showing only the papers cited on the current notebook (see https://jupyterbook.org/content/citations.html#local-bibliographies).

cc @martinacantaro

**Comment by martinacantaro** [comment]
I'm for it. How should we proceed in order to activate bibtex?
