### ISSUE TITLE
GLM binomial regression

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#214]
**Notebook url**: https://github.com/pymc-devs/pymc-examples/blob/main/examples/generalized_linear_models/GLM-binomial-regression.ipynb

**Comment by OriolAbril** [comment]
It could have a couple nits related to ArviZ and xarray updated but it is basically best practices, classifying as general updates mostly for completeness

**Comment by drbenvincent** [comment]
Can this issue be closed now we have a v4 version?

**Comment by OriolAbril** [comment]
yes, sorry I forgot to update the project and close the issue.
