### ISSUE TITLE
air passengers prophet

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#215]
**Notebook url**: https://github.com/pymc-devs/pymc-examples/blob/main/examples/time_series/Air_passengers-Prophet_with_Bayesian_workflow.ipynb
reviewer: @MarcoGorelli

**Comment by OriolAbril** [comment]
the versions between the first cell printout and the watermark don't match. It should be reexecuted to fix that. I think this is due to the `v4` branch having `3.11.1` as version in the init for quite a while and that the notebook was executed all at once sequentially on v4, but it will probably be very confusing to readers.

**Comment by danhphan** [comment]
Hi @OriolAbril let me re-executed this notebook. Thanks
