### ISSUE TITLE
Add definitions of common terms to the Glossary

### ISSUE THREAD

**Issue by martinacantaro** [pymc-devs/pymc-examples#222]
**Goal**
Building a useful Glossary with definitions of common terms, that can be linked to from the documents.

**How to contribute**
 1. Pick a term from the list below, excluding those labeled `in progress` (those have already been picked)
 2. Comment this issue to inform us that you are working on it.
 3. Make a PR editing the [docs/source/glossary.md](https://github.com/pymc-devs/pymc3/tree/main/docs) file following [this format](https://jupyterbook.org/content/content-blocks.html?highlight=glossary#glossaries)
 4. Include the following ID string in your PR title or commit message (this will help us keep track of it in Clickup): CU-5t5y0p

**List of terms:**
* Equidispersion `(in progress)`
* Underdispersion `(in progress)`
* Overdispersion `(in progress)`
* Generalized Poisson PMF `(in progress)`
* Bayes' theorem `(in progress)`
* Prior `(in progress)`
* Posterior `(in progress)`
* Markov Chain (MC) and Markov Chain Monte Carlo (MCMC) `(in progress)`
* Probability density `(in progress)`
* Probability mass
* Maximum a Posteriori (MAP)
* Maximum Likelihood Estimation (MLE) `(in progress)`
* No-U-Turn-Sampler (NUTS)
* Hamiltonian Monte Carlo
* Credibility
* Ordinary Differential Equation (ODE)
* Hierarchical Ordinary Differential Equation
* Generalized Linear Model (GLM) `(in progress)`

**Comment by Guneetconvent2002** [comment]
This is my first time contributing to something open-source and I have this question that one might find really silly but I really have that problem. I am not able to find any directory named docs in this repository. Could you maybe help me?? Or do I have to make a directory named docs?

**Comment by Sayam753** [comment]
This docs directory is in pymc3 repo. Find the directory [here](https://github.com/pymc-devs/pymc3/tree/main/docs).

**Comment by Guneetconvent2002** [comment]
Okay, I'll start working on it

**Comment by martinacantaro** [comment]
Hi! Thank you for contributing @Guneetconvent2002 ! I hope your first open source contribution goes really well, let us know if you need any assistance. 

I updated the description to add the details you pointed out. 

"In progress" means somebody is already working on that definition, so pick any of the others!

**Comment by OriolAbril** [comment]
@Guneetconvent2002 In progress means someone is already working on that term. I'd recommend choosing 2-3 terms,  commenting here which and then open a pr to pymc3 with the definitions.

You can use https://github.com/pymc-devs/pymc3/pull/4984 as an example of pr adding definitions to the glossary.

@everyone this is also related to https://github.com/pymc-devs/pymc3/issues/4899 so we should probably close one of the two. This one has somewhat better explanation and is correctly labeled whereas the other one is in the right repo I think. @martinacantaro can you merge the two issues into one?

Also one extra comment which is whether the terms should be alphabetically sorted (excluding the two example ones that should be removed eventually)

**Comment by Guneetconvent2002** [comment]
I'll be doing Equidispersion, Generalized poisson pmf, Bayes' theorem, Markov Chain (MC) and Markov Chain Monte Carlo (MCMC)

**Comment by martinacantaro** [comment]
Awesome! Updated them as "in progress"

**Comment by Guneetconvent2002** [comment]
I have made a PR please have a look

**Comment by martinacantaro** [comment]
Hi! Following @OriolAbril's suggestion, I'm closing this issue and moving it to https://github.com/pymc-devs/pymc3/issues/4899

@Guneetconvent2002, I left some comments on [your PR](https://github.com/pymc-devs/pymc3/pull/4986)
