### ISSUE TITLE
Spline example

### ISSUE THREAD

**Issue by jhrcook** [pymc-devs/pymc-examples#230]
# Notebook proposal
**Title**: Spline example

## Why should this notebook be added to pymc-examples?
There are no example notebooks for modeling a spline. I have a good example that I have linked to previously on the PyMC3 discourse and it has had a good reception.

## Related notebooks
I do not see any other spline example notebooks so I believe this would be a new notebook.

# References
I have previously published the code and examples on my personal blog [here](https://joshuacook.netlify.app/post/pymc3-spline/), but it is not the actual Jupyter notebook. I still have the notebook and it should be pretty easy to update and adjust to the prescribed Jupyter Notebook style.

**Comment by canyon289** [comment]
Hi Josh! This sounds like a great idea. Converting your blog post into a notebook and adding it to the examples would be a fantastic contribution

**Comment by jhrcook** [comment]
In my example, I use the cherry blossom data from Statistical Rethinking. Should I use a link to the file on McElreath's repository or download the data and add it to the "examples/data/" directory in this repository and using the `try: ... except: ...` pattern described in the style guide?

**Comment by canyon289** [comment]
Download the data and put it in the example repo. 
Be sure to give give credit somewhere to Richard

As for the try except I cant recall the style guide but dont let that stop you. Id say put up the PR and we can help you from there

**Comment by jhrcook** [comment]
> Download the data and put it in the example repo. Be sure to give give credit somewhere to Richard
> 
> As for the try except I cant recall the style guide but dont let that stop you. Id say put up the PR and we can help you from there.
> 
> Than you for following up

Thank you for the quick response. I am referencing [this](https://github.com/pymc-devs/pymc/wiki/PyMC3-Jupyter-Notebook-Style-Guide#reading-from-file) suggestion in the style guide where the following pattern is recommended:

```python
try:
    df_all = pd.read_csv(os.path.join("..", "data", "file.csv"), ...)
except FileNotFoundError:
    df_all = pd.read_csv(pm.get_data("file.csv"), ...)
```

I’ll go ahead and implement it because the cherry blossom data will be in the “examples/data/” directory.

**Comment by canyon289** [comment]
Ah yes please do that. Thank you for reading the style guide
