### ISSUE TITLE
Splines in PyMC

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#234]
**Notebook url**: https://github.com/pymc-devs/pymc-examples/blob/main/examples/splines/spline.ipynb
reviewer: jhrcook

**Comment by OriolAbril** [comment]
The notebook needs to be updated to follow the [style guide](https://github.com/pymc-devs/pymc/wiki/PyMC-Jupyter-Notebook-Style-Guide). All notebooks **must** have a post directive in their first cell.

Ideally it would also use matplotlib directly instead of plotnine to reduce the dependencies on external libraries

**Comment by michaelosthege** [comment]
The notebook should also mention the `SplineWrapper` and explain the difference to the spline built in the notebook.
https://github.com/pymc-devs/pymc/blob/073e26b9c650ff9ae851ab9904cb3ad9c905a643/pymc/distributions/dist_math.py#L316-L319

**Comment by OriolAbril** [comment]
Updated by https://github.com/pymc-devs/pymc-examples/pull/274, moving it to v4 auto to signal there are still changes needed on the metadata. 

See https://github.com/pymc-devs/pymc-examples/pull/274#discussion_r867411416

**Comment by kuvychko** [comment]
Working on this notebook, as part of PyMC Open Source session #2 with @PrinceAsiedu
