### ISSUE TITLE
Port NBs from PyMC3 to PyMC

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#236]
**URGENT**: Update all references to the style guide. The style guide has been renamed so the link now needs to be updated from all the places where it used to be present as they are now broken. For example the one in https://github.com/pymc-devs/pymc-examples/blob/main/CONTRIBUTING.md#pull-request-checklist

Change all occurrences of PyMC3 to PyMC. **IMPORTANT** The change should happen as the notebooks are updated to use v4. Until the beta release is out, notebooks should still use PYMC3 name and use 3.11.x version as they will still be part of the pymc3 docs at https://pymc.readthedocs.io/en/v3.11.4/

side note, feel free to split in two different issues.

cc @martinacantaro  @canyon289

**Comment by drbenvincent** [comment]
Now we've released v4, the urgency of this has diminished. So we could close this issue and fall back to #333?

**Comment by twiecki** [comment]
Closing in favor of #333.
