### ISSUE TITLE
"Bad" SMC example doesn't actually "fail spectacularly"

### ISSUE THREAD

**Issue by JohnGoertz** [pymc-devs/pymc-examples#242]
**Sequential Monte Carlo**:
**https://docs.pymc.io/en/stable/pymc-examples/examples/samplers/SMC2_gaussians.html**:

## Issue description
Ironically, this issue is about something working better than expected. The SMC example notebook has a [Kill your darlings](https://docs.pymc.io/en/stable/pymc-examples/examples/samplers/SMC2_gaussians.html#Kill-your-darlings) section intended to demonstrate how SMC can perform poorly with high dimensionality. However, for me, it performs basically just fine. 

## Expected output
4-D example online: 
![image](https://user-images.githubusercontent.com/9869969/137707672-7d749d48-8eb1-4d93-8eb4-28ba2ed89e17.png)
40-D example online:
![image](https://user-images.githubusercontent.com/9869969/137707738-57885726-61ad-4cc7-94fe-90e3fab1d7d4.png)

## Observed output
Note that, for better or for worse, I observed the output of the 4-D to be _worse_ than what's online (or, at least, less smooth), while the 40-D is better than what's online.

4-D example for me:
![image](https://user-images.githubusercontent.com/9869969/137707864-af9c80d8-f4de-4855-a86d-7f707a8760d8.png)
40-D example for me:
![image](https://user-images.githubusercontent.com/9869969/137707935-21fd80ae-22ef-48dd-a146-e9310663d20a.png)
40-D ESS summary for me:
![image](https://user-images.githubusercontent.com/9869969/137708207-55aa13b8-2c65-4364-867b-26ef1135d597.png)

## Proposed solution
The notebook was last run with PyMC v3.9.1. My environment has:
PyMC v3.11.4
Arviz v0.11.2
Theano v1.1.2

Maybe SMC has been improved in the past few versions, and this problem needs to be made harder?

**Comment by JohnGoertz** [comment]
That's really interesting that there's such a big difference between the two. Perhaps the notebook should be updated at that point to indicate that switching from the (then-default) Metropolis to Independent-Metropolis can recover performance, and maybe a brief discussion as to when one would be preferable over the other?

**Comment by ricardoV94** [comment]
The thing is that the old method was completely removed in V3

**Comment by aloctavodia** [comment]
Hi @JohnGoertz thanks for reporting this issue. Maybe the PyMC motto should be "better than expected", haha. Joking aside, I have updated the notebook example. 

So far in our experiments we have not found an example where the Metropolis kernel performs better than the Independent-Metropolis Kernel. The main reason to re-introduce the Metropolis kernel in PyMC (version 4) was to make it easier to run further experiments comparing these two kernels.
