### ISSUE TITLE
Rolling regression uses glm submodule, can easily be fixed

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc-examples#256]
**Notebook title**:Rolling Regression
**Notebook url**: https://docs.pymc.io/en/v3/pymc-examples/examples/generalized_linear_models/GLM-rolling-regression.html

## Issue description
It's currently using the glm submodule for the linear model, this can easily be changed to just use a direct implementation.

**Comment by OriolAbril** [comment]
This has been updated already: https://docs.pymc.io/projects/examples/en/latest/generalized_linear_models/GLM-rolling-regression.html?highlight=Rolling%20regression. That link is not updated because it is the v3 documentation
