### ISSUE TITLE
How to ask a question on discourse notebook

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#258]
# Notebook proposal
**Title**: How to ask a question on discourse

## Why should this notebook be added to pymc-examples?
Many questions on discourse have non reproducible examples, way too wide scopes and/or very basic formatting issues that make answering much harder. I think it would be very useful to have a notebook like this, not sure if here or on pymc repo.

cc @martinacantaro 

## Related notebooks
none of the notebooks we have so far are remotely related to this one

# References
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports would be a good inspiration, but more focused on discourse questions instead of bug reports.

**Comment by cluhmann** [comment]
I like the idea of having a place to point discourse users who are asking questions in less-than-optimal ways.  I'm not sure it belongs in the examples (but it might).  [This](https://stackoverflow.com/help/how-to-ask) is my "go to" description of how to ask programming-related questions.  That page also links to [this blog post](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/) which may also be of some help.

**Comment by twiecki** [comment]
Agree with @cluhmann that it's useful but probably not in examples.

**Comment by cluhmann** [comment]
We might consider combining this with an updated (and revised) version of the [FAQ](https://discourse.pymc.io/t/frequently-asked-questions/74) @junpenglao created on discourse.  Most of those answers were written quite a while ago (e.g., pre-v3.5?) and the answers will only continue to age.

**Comment by OriolAbril** [comment]
updating the faqs is a great idea (I am always partial towards having it on the documentation where everyone can contribute to and we have more style and formatting options, but anywhere would be fine). But I would keep the two things independent, and add a check on the how to ask about "going over the faq to avoid duplication" linking to the faq page

**Comment by cluhmann** [comment]
Closed by https://github.com/pymc-devs/pymc.io/pull/36.  The issue of the FAQs can be raised in a new issue/proposal if someone wishes.
