### ISSUE TITLE
Make use of new pm.Censored in notebooks about censored data

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc-examples#261]
**Notebook title**:
* Censored Data Models 
* Bayesian regression with truncated or censored data

**Notebook url**: 
* https://docs.pymc.io/en/v3/pymc-examples/examples/survival_analysis/censored_data.html
* https://docs.pymc.io/en/v3/pymc-examples/examples/generalized_linear_models/GLM-truncated-censored-regression.html

## Issue description
After https://github.com/pymc-devs/pymc/pull/5169 we will have native Censored distributions in PyMC. The examples should be updated to make use of them.

The workflow in the second notebook is actually being used as the test for the Censored distributions in: https://github.com/pymc-devs/pymc/blob/d9e7db08ef368981be83bb2c9aba824da92be856/pymc/tests/test_distributions.py#L3281-L3322

Truncated distributions will only come later after https://github.com/aesara-devs/aeppl/issues/96, but then we should re-update the notebooks to make use of them.

**Comment by OriolAbril** [comment]
Cc @drbenvincent

**Comment by drbenvincent** [comment]
Happy for you to assign this to me @OriolAbril
