### ISSUE TITLE
binning notebook

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#270]
Notebook url: https://github.com/pymc-devs/pymc-examples/blob/main/examples/case_studies/binning.ipynb
reviewer: drbenvincent, ericmjl

**Comment by cuchoi** [comment]
Working on this one

**Comment by drbenvincent** [comment]
Done :)

**Comment by PrinceAsiedu** [comment]
Working on this

**Comment by PrinceAsiedu** [comment]
I think I have to move to another notebook because this already has the opening and closing cells I intended on adding to the notebook
@reshamas
