### ISSUE TITLE
Reinforcement Learning Model for behavioral data

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc-examples#272]
# Notebook proposal
**Title**: Reinforcement Learning Model for behavioral data

## Why should this notebook be added to pymc-examples?

I wrote this notebook some time ago: https://github.com/ricardoV94/stats/blob/master/modelling/RL_PyMC.ipynb and shared it on the Discourse, where it seems to have been quite popular: https://discourse.pymc.io/t/fitting-a-simple-reinforcement-learning-model-to-behavioral-data-with-pymc3-jupyter-nb/4651

## Related notebooks
I don't know any related notebooks...

# References
Hopefully the base notebook is good enough. I can provide more references if necessary

***

## Notes
I have been meaning to adapt this into an official pymc-examples notebook but I simply can't find the time. I am happy to assist anyone who wants to work on this, and I have no issues if the final version modifies/extends/trims it or if it doesn't resemble the original at all!

The original code was written in Theano, but I think everything will work fine with the equivalent Aesara imports.

**Comment by juanitorduz** [comment]
@ricardoV94 I need to learn about this topic and your notebook is a hidden gem ;) I have seen your last update (commit) was a month ago. Will you push this notebook to the finish line or do you need some support? I'll be happy to help. Great work (as always)!

**Comment by ricardoV94** [comment]
@juanitorduz If you mean adding it to pymc-examples, it's up for grabs. I don't plan to work on it in the foreseeable future.

If you want to extend it, many people have asked how to include multiple participants/experiments and not just a single one as in the example.

**Comment by juanitorduz** [comment]
Yes, put it into the docs! I suggest (as I am not an expert in the subject) format the notebook in order to publish it in the docs , get feedback and iterate.

**Comment by ricardoV94** [comment]
> Yes, put it into the docs! I suggest (as I am not an expert in the subject) format the notebook in order to publish it in the docs , get feedback and iterate. 

That would be great!
