### ISSUE TITLE
pymc4 Does not open on Jupyter notebook

### ISSUE THREAD

**Issue by muharrembb** [pymc-devs/pymc-examples#284]
Hello,

I installed pymc4 as instructed from your git account. New pymc is working well when I open python on my terminal. However, when I open Jupiter notebook and try to import pymc, it gives an error. I uninstalled mini forge and all environment and reinstalled them again. However, still I am not able to use
 pymc by using jupyter notebook. Any advice?

![Screen Shot 2022-02-20 at 10 14 39 PM](https://user-images.githubusercontent.com/22571068/154883532-c244e919-2e34-4162-8ce5-ee2890f4670d.png)
![Screen Shot 2022-02-20 at 10 13 41 PM](https://user-images.githubusercontent.com/22571068/154883542-82ebfde8-e691-4294-948b-3deb57137137.png)

![Screen Shot 2022-02-20 at 10 18 23 PM](https://user-images.githubusercontent.com/22571068/154883611-9c27a420-651c-4996-a93d-68537dbf4af5.png) --- it is workin when I open python on terminal.

**Comment by cfonnesbeck** [comment]
Hello, @muharrembb. Please open a discussion on our [Discourse page](https://discourse.pymc.io/) for help in setting up PyMC.

**Comment by muharrembb** [comment]
Thanks! I will!
