### ISSUE TITLE
Getting started notebook is outdated

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc-examples#31]
For example here are the Installation instructions:

> # Installation
> Running PyMC3 requires a working Python interpreter, either version 2.7 (or more recent) or 3.5 (or more recent); we recommend that new users install version 3.5. A complete Python installation for Mac OSX, Linux and Windows can most easily be obtained by downloading and installing the free Anaconda Python Distribution by ContinuumIO.

https://github.com/pymc-devs/pymc-examples/blob/main/examples/getting_started.ipynb

**Comment by OriolAbril** [comment]
Let's keep in mind that this is without any doubt the most visited notebook in the docs, so even the tiniest changes can have a huge impact on the project overall. 

It may also be worth to redeploy the docs right after this is updated, even if it's the only change since the last deployment.

**Comment by ricardoV94** [comment]
Other things: 
1. Probably it's better to just remove the `find_MAP` demonstration at this point?
2. This is severely outdated: 
> PyMC3, Stan (Stan Development Team, 2014), and the LaplacesDemon package for R are currently the only PP packages to offer HMC.

**Comment by Aut0R3V** [comment]
> Some specifics that jump to mind:
> 
> 1. Probably it's better to just remove the `find_MAP` demonstration at this point? Maybe introduce prior and posterior predictive sampling instead?
> 2. This is severely outdated:
> 
> > PyMC3, Stan (Stan Development Team, 2014), and the LaplacesDemon package for R are currently the only PP packages to offer HMC.
> 
> 3. Variational inference is mentioned as a missing feature (and no reference to SMC either)

@ricardoV94 I'm interested in working for this. To begin with, the find_MAP  demonstration has been removed through this pull request - https://github.com/pymc-devs/pymc-examples/pull/145

For the second point, what changes can be made?
Can you please explain the third point?
Thanks!

**Comment by symeneses** [comment]
Is this issue still needed? The notebook mentioned is not in the `main` branch anymore.

**Comment by twiecki** [comment]
Weird, it indeed seems to have gone. Couldn't find where it went either.

**Comment by OriolAbril** [comment]
This is now the pymc overview notebook: https://docs.pymc.io/en/latest/learn/core_notebooks/pymc_overview.html. It has alrrady been ported to v4 and as part of the versioned docs it is executed automatically every time we build the docs. We forgot to close this issue though, doing it now
