### ISSUE TITLE
Implement nbsphinx gallery

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc-examples#327]
We would like to bring the NB gallery from v3 back

The old code was customly written, which makes maintenance harder.

`nbsphinx` allows to include NBs in sphinx and has a gallery feature that is described here: https://nbsphinx.readthedocs.io/en/0.8.8/subdir/gallery.html

**Comment by canyon289** [comment]
Hard agree, I actually dont think I would have ended up using PyMC or been Bayesian at all the notebook gallery. 

The notebook gallery
* Clearly shows whats possible with images, not description
* Is a self contained narrative in each notebook
* Is runnable 

There's nothing else quite like it

![image](https://user-images.githubusercontent.com/7213793/170509809-2e1df6d4-7e29-45d8-9a34-9db15f6f8086.png)

**Comment by OriolAbril** [comment]
We no longer use nbsphinx, so the key thing is seeing if it is possible to use it for generating the cards but not to render the notebooks so we can continue to use sphinx directives, cross-references... We are still using only the tip of the iceberg of all these new features, but I'd rather adapt the sphinx extension than renounce to cross-references and targets, figures with captions and alt text, tags, other directives like dropdowns...

> Clearly shows whats possible with images, not description
> Is a self contained narrative in each notebook
> Is runnable

The last two items are not a property of the card view but of the notebooks itself. This has never changed and won't change. The only thing in discussion is what is the best way to generate the card view from the notebooks and folder hierarchy, that it would be best to generate that again is also not being discussed.

**Comment by twiecki** [comment]
I got a good part of the way here: https://github.com/pymc-devs/pymc-examples/pull/328
