### ISSUE TITLE
GLM in PyMC3: Out-Of-Sample Predictions Example

### ISSUE THREAD

**Issue by juanitorduz** [pymc-devs/pymc-examples#33]
Hi 👋 ! I am very interested in the `glm` module of PyMC3, specially using it for prediction problems. There is an active thread about this topic: [“Out of sample” predictions with the GLM sub-module](https://discourse.pymc.io/t/out-of-sample-predictions-with-the-glm-sub-module/773). I wrote a small post summarising the potential solutions : https://juanitorduz.github.io/glm_pymc3/  Is this something you would be interested in having on the [examples](https://docs.pymc.io/nb_examples/index.html)? If so, is it ok as it is now or do you want me to reduce it a just focus on the out-of-sample section. I am happy to contribute to the documentation 🚀 .

**Comment by ricardoV94** [comment]
@juanitorduz, sorry for the delay! From checking that discourse thread, it seems there is a strong need for a concise example on how to do out of sample predictions for GLM models. 

I think your blog does a good job so it would probably be a good addition to the examples gallery. 

I would think that we might already have some examples buried in other longer glm notebooks, so if you could link to those at the end of your notebook that would be great (even if they don't use Patsy). If we really have no other examples, that makes an even stronger care for your addition.

Pinging @AlexAndorra for input.

**Comment by juanitorduz** [comment]
I created an initial PR https://github.com/pymc-devs/pymc-examples/pull/37
