### ISSUE TITLE
Standardize and Update Notebook Gallery

### ISSUE THREAD

**Issue by AlexAndorra** [pymc-devs/pymc-examples#34]
[BEGINNER-FRIENDLY]
Our [notebooks gallery is quite big](https://github.com/pymc-devs/pymc3/tree/master/docs/source/notebooks), so: 
- Many of them use an old style and could use an updating with ArviZ color style instead (not listed).
- Many notebooks show `FutureWarnings` that should be addressed (not listed).
- Some notebooks fail to run because they use outdated third-party APIs or exotic packages (listed below).

So this issue is here to signal it would be nice if people want to take some time updating and re-running the notebooks below **with PyMC 3.9**, [according to this style page](https://github.com/pymc-devs/pymc3/wiki/PyMC's-Jupyter-Notebook-Style) 🎉 
Do it in small batches though, to not get bored and enjoy it 😉 Thanks a lot in advance for your help and don't hesitate to ask your questions below!
PyMCheers 🖖 

Here is an up-to-date list of the most outdated and problematic NBs (those not listed here should be checked for style and updating accordingly):

### Exotic
+ [ ] `blackbox_external_likelihood` needs Cython
+ [ ] `convolutional_vae_keras_advi` needs Keras

### Other Issues
+ [ ] `GLM` theano.gof.fg.MissingInputError
+ [x] `GLM-poisson-regression` KeyError: "['hpd_2.5', 'hpd_97.5'] not in index"
+ [ ] `GLM-negative-binomial-regression` KeyError: "['hpd_97.5', 'hpd_2.5'] not in index"
+ [ ] `GLM-model-selection` KeyError: 'var names: "[\'sd_log__\'] are not present" in dataset'
+ [x] `GP-MaunaLoa2` ValueError: Units 'M' and 'Y' are no longer supported
+ [x] `GP-MaunaLoa` ValueError: Units 'M' and 'Y' are no longer supported, as they do not represent unambiguous timedelta values durations.
+ [ ] `GP-TProcess` runs but has way too many divergences; timed out after 14_000 seconds
+ [x] `PyMC3_tips_and_heuristic` KeyError: Rhat
+ [ ] `dependent_density_regression` AttributeError: 'DataFrame' object has no attribute 'range'
+ [x] `hierarchical_partial_pooling` not enough values to unpack (expected 2, got 1)
+ [ ] `lda-advi-aevb` TypeError: __init__() got an unexpected keyword argument 'n_topics'
+ [x] `marginalized_gaussian_mixture_model` AttributeError: 'Rectangle' object has no property 'normed'
+ [x] `GLM-logistic` AttributeError: 'Rectangle' object has no property 'normed'
+ [x] `model_averaging` FileNotFoundError: File ../data/milk.csv does not exist
+ [x] `model_comparison` AttributeError: 'ELPDData' object has no attribute 'WAIC'
+ [x] `multilevel_modeling` More chains (4000) than draws (2) and some plots may be wrong
+ [x] `profiling` has a shape error
+ [ ] `rugby_analytics` ValueError: not enough values to unpack (expected 2, got 1)
+ [ ] `sampling_callback` has a shape error (looks like a threading problem)
+ [ ] `survival_analysis` cell 11 raises a NotImplementedError in numpy/pandas
+ [x] `weibull_aft` AttributeError: module 'statsmodels' has no attribute 'datasets'
+ [ ] `ODE_with_manual_gradients` ValueError: array must not contain infs or NaNs

**Comment by OriolAbril** [comment]
closing this in favour of the [tracker project](https://github.com/pymc-devs/pymc-examples/projects/1) and all the other issues (each notebook has its own issue now)
