### ISSUE TITLE
Gallery page is missing howtos, tutorials, and deep-dives

### ISSUE THREAD

**Issue by drbenvincent** [pymc-devs/pymc-examples#353]
As far as I can tell, none of the notebooks in [`examples/pymc3_howto`](https://github.com/pymc-devs/pymc-examples/tree/main/examples/pymc3_howto) folder are currently included/rendered in the examples page https://www.pymc.io/projects/examples/en/latest/gallery.html. They _are_ there when looking for them via the tags, but they are not rendered on the gallery page.

**Comment by twiecki** [comment]
Yeah, just need to add them, it's quite simple.
