### ISSUE TITLE
Remove `pymc.*` and `pymc3.*` tags from left bar on website

### ISSUE THREAD

**Issue by drbenvincent** [pymc-devs/pymc-examples#374]
Do we have agreement that removing these tags from the left of the site is a good idea?
<img width="341" alt="Screenshot 2022-06-10 at 13 27 30" src="https://user-images.githubusercontent.com/6765047/173063995-b910e27d-b6f8-404d-ba02-8140eb1ad929.png">

If so, would that be done with a PR which manually removes all such tags from all example notebooks? Or would it be done by some clever filtering web code in https://github.com/pymc-devs/pymc.io ?

If it's the former then I can probably do that. If it's the latter than I can't, or would need some help.

**Comment by OriolAbril** [comment]
Yes, they all need to be removed. I am not sure about a PR removing them all at once, there are many notebooks with open PRs to update them to v4. Creating git conflicts for this seems too much trouble for what willbe getting fixed.

I'd suggest reviewing all open PRs to make sure if they are editing a notebook with those tags they get removed and a PR removing them for those without open PRs

**Comment by twiecki** [comment]
We could probably write a small script to do them all.

**Comment by drbenvincent** [comment]
Nearly there. Not done this kind of stuff before so maybe I'm missing something very simple. 

```python
import os
import codecs
import re
from copy import copy


exclude_directories = set(['.ipynb_checkpoints'])
filelist = []
for root, dirs, files in os.walk(path):
    dirs[:] = [d for d in dirs if d not in exclude_directories]
    for file in files:
        file_extension = os.path.splitext(file)[1]
        if file_extension == ".ipynb":
            filelist.append(os.path.join(root,file))
        
        
for file in filelist:
    print(f"\n{file}")
    target = None
    
    # read file
    f = codecs.open(file, 'r')
    source = f.read()
    
    # extract tags text
    target = re.findall(r'":tags:(.+?)\\n', source)
    
    if len(target) == 0:
        print("\tno tags found")
        continue
        
    target = target[0] + ","
    print(f"\tTAGS FOUND: {target}")
    
    # extract tags to remove
    kill_these = re.findall(r'(pymc)(.+?,)', target)
    kill_these = [''.join(tups) for tups in kill_these]
    if len(kill_these) == 0:
        print("\tno changes to be made")
        continue
        
    print(f"\tTAGS TO REMOVE: {kill_these}")
    
    new = copy(target)
    for to_kill in kill_these:
        new = new.replace(to_kill, "")
        
    print(f"\t REPLACE WITH: {new}")
    
    # replace
    source = source.replace(target, new)  # <------- this does not seem to work
    print(source[:500])
    
    # TODO: write to file here
```

**Comment by drbenvincent** [comment]
So this seems like a better approach, and that it _should_ work. 

```python
import json
import os
    
path = "examples"
exclude_directories = set(['.ipynb_checkpoints'])
filelist = []
for root, dirs, files in os.walk(path):
    dirs[:] = [d for d in dirs if d not in exclude_directories]
    for file in files:
        file_extension = os.path.splitext(file)[1]
        if file_extension == ".ipynb":
            filelist.append(os.path.join(root,file))

for file in filelist:
    with open(file, 'r+') as openfile:
        json_object = json.load(openfile)

        for i, string in enumerate(json_object['cells'][0]['source']):
            if string.startswith(":tags:"):
                elements = string.split()
                filtered_elements = [token for token in elements if not token.startswith('pymc')]
                new = " ".join(filtered_elements)
                # update the dictionary
                json_object['cells'][0]['source'][i] = new
                # write out to disk
                json.dump(json_object, openfile)
                # end the iteration
                break
```

But the resulting `.ipynb` files are not readable. Error when trying to open an edited file in Jupyter lab:
```
Unreadable Notebook: /Users/benjamv/git/pymc-examples/examples/generalized_linear_models/GLM-binomial-regression.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...')
```

Any ideas what's going on here?

**Comment by michaelosthege** [comment]
Can you post a few lines of before/after JSON?

Just a rough guess, but from looking at the code this could be a lot easier to do with RegEx via `re.sub(pattern, replacement, text)`.

Otherwise, if the JSON looks fine visually, double check the encoding. Jupyter is a little picky about that.

**Comment by drbenvincent** [comment]
start
```
{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "domestic-remove",
   "metadata": {},
   "source": [
    "(GLM-binomial-regression)=\n",
    "# Binomial regression\n",
    "\n",
    ":::{post} February, 2022\n",
    ":tags: binomial regression, generalized linear model, pymc.Binomial, pymc.ConstantData, pymc.Deterministic, pymc.Model, pymc.Normal, pymc3.Binomial, pymc3.ConstantData, pymc3.Deterministic, pymc3.Model, pymc3.Normal\n",
    ":category: beginner\n",
    ":author: Benjamin T. Vincent\n",
    ":::"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "72588976-efc3-4adc-bec2-bc5b6ac4b7e1",
   "metadata": {},
   "source": [
    "This notebook covers the logic behind [Binomial regression](https://en.wikipedia.org/wiki/Binomial_regression), a specific instance of Generalized Linear Modelling. The example is kept very simple, with a single predictor variable. \n",
    "\n",
```

end
```

```

**Comment by drbenvincent** [comment]
> Just a rough guess, but from looking at the code this could be a lot easier to do with RegEx via `re.sub(pattern, replacement, text)`.

Quite possibly, but I'm not that experienced with regular expressions. 

> Otherwise, if the JSON looks fine visually, double check the encoding. Jupyter is a little picky about that.

Will take a look

**Comment by michaelosthege** [comment]
It might be enough to do `.replace("pymc.", "").replace("pymc3.", "")` on the entire document here.
In the code we don't usually have `pymc.` occurences and in the end you'll see it in the git diff.

If you open the project with VS Code, you could even do this with the Find & Replace across all files (Ctrl+Shift+H).

If you want to continue the programmatic route, maybe unindent your `json.dump` lines out of the `for` loop?
Also pass `json.dump(..., indent=2)` to get the output nicely formatted.

**Comment by drbenvincent** [comment]
The formatting and the end of the file seems messed up. Problem seems to happen even if you just write the file with zero changes to it.

**Comment by michaelosthege** [comment]
But then it's definitely an encoding issue. VS Code shows the encoding in the bottom right corner.
You'll probably have to specify the encoding like here:

https://github.com/pymc-devs/pymc-examples/blob/c323de9a39cc91e55ea6e0339cfd380add6bd49d/scripts/rerun.py#L52-L58

**Comment by drbenvincent** [comment]
> It might be enough to do `.replace("pymc.", "").replace("pymc3.", "")` on the entire document here. In the code we don't usually have `pymc.` occurences and in the end you'll see it in the git diff.

Well we want to remove the whole tag, not just the `pymc` prefix. So I'm not sure if that will work


> If you want to continue the programmatic route, maybe unindent your `json.dump` lines out of the `for` loop? Also pass `json.dump(..., indent=2)` to get the output nicely formatted.

That definitely helps. Although I think the issue is something fundamental with writing to the file... if I comment out any changes so you just read and write the file then the problem stays the same

**Comment by drbenvincent** [comment]
Got it. The file read/write pattern used in `rerun.py` works.

```python
import json
import os


path = "examples"
exclude_directories = set(['.ipynb_checkpoints'])
filelist = []
for root, dirs, files in os.walk(path):
    dirs[:] = [d for d in dirs if d not in exclude_directories]
    for file in files:
        file_extension = os.path.splitext(file)[1]
        if file_extension == ".ipynb":
            filelist.append(os.path.join(root,file))

for filename in filelist:

    with open(filename, "r", encoding="utf-8") as file:
        lines = file.read()
        json_object = json.loads(lines)
    
    made_changes = False
    for i, string in enumerate(json_object['cells'][0]['source']):
        if string.startswith(":tags:"):
            elements = string.split()
            filtered_elements = [token for token in elements if not token.startswith('pymc')]
            new = " ".join(filtered_elements)
            # update the dictionary
            json_object['cells'][0]['source'][i] = new
            made_changes = True
            break
            
    if made_changes:
        json_string = json.dumps(json_object)
        with open(filename, "w", encoding="utf-8") as file:
            file.write(json_string)
```

**Comment by drbenvincent** [comment]
This is mostly done. All we need to do now is ensure all pull requests remove any `pymc*` tags.
