### ISSUE TITLE
add notebooks in `learn/core_notebooks` to the main examples gallery

### ISSUE THREAD

**Issue by drbenvincent** [pymc-devs/pymc-examples#379]
Following quick discussion here https://github.com/pymc-devs/pymc-examples/issues/83#issuecomment-1159736382 we'll add the notebooks of core features (listed here https://www.pymc.io/projects/docs/en/stable/learn/core_notebooks/index.html) to the main set of examples here https://www.pymc.io/projects/examples/en/latest/gallery.html.

Add as the first section in the gallery

Core notebook files are located here https://github.com/pymc-devs/pymc/tree/main/docs/source/learn/core_notebooks

**Comment by OriolAbril** [comment]
We'll need to upload the images locally (or generate custom thumbnails) and then use the grid directive with links of `ref` type. something like:

```
:::{grid} 1 2 3 4
:::{grid-item-card} 
:class-item: p-2 
:img-top: thumbnail_overview.png
:link: pymc:pymc_overview
:link-type: ref

PyMC Overview
:::
same for other notebooks
::::
```

**Comment by drbenvincent** [comment]
And that goes at the top of `gallery.rst` in the pymc-examples repo?

**Comment by OriolAbril** [comment]
yep (didn't realize it was rst, updated the directives
