### ISSUE TITLE
Updating the example "Getting started with PyMC4: Bayesian neural networks" from Martin Krasser

### ISSUE THREAD

**Issue by caxelrud** [pymc-devs/pymc-examples#384]
I looking forward to update the following example to the current pymc:
"Getting started with PyMC4: Bayesian neural networks - Martin Krasser"
https://nbviewer.org/github/krasserm/bayesian-machine-learning/blob/dev/bayesian-neural-networks/bayesian_neural_networks_pymc4.ipynb
The example uses tensorflow and have the following line (full model follows):
 `return activation(tf.tensordot(x, w, axes=[1, 0]) + b)
`What will be current replacement for this tensorflow line?

Model Code:
```
@pm.model
def layer(name, x, n_in, n_out, prior_scale, activation=tf.identity):
    w = yield pm.Normal(name=f'{name}_w', loc=0, scale=prior_scale, batch_stack=(n_in, n_out))
    b = yield pm.Normal(name=f'{name}_b', loc=0, scale=prior_scale, batch_stack=(1, n_out))
    
    return activation(tf.tensordot(x, w, axes=[1, 0]) + b)

@pm.model
def model(x, y, prior_scale=1.0):    
    o1 = yield layer('l1', x, n_in=1, n_out=5, prior_scale=prior_scale, activation=tf.nn.relu)
    o2 = yield layer('l2', o1, n_in=5, n_out=5, prior_scale=prior_scale, activation=tf.nn.relu)
    o3 = yield layer('l3', o2, n_in=5, n_out=1, prior_scale=prior_scale)
    
    yield pm.Normal(name='obs', loc=o3, scale=noise, observed=y)
```

**Comment by GarvitDadheech** [comment]
Hey @caxelrud , I think we can replace the TensorFlow operations with PyMC equivalents as the following -

```python
import pymc as pm

@pm.model
def layer(name, x, n_in, n_out, prior_scale, activation=pm.math.identity):
    w = yield pm.Normal(name=f'{name}_w', mu=0, sigma=prior_scale, shape=(n_in, n_out))
    b = yield pm.Normal(name=f'{name}_b', mu=0, sigma=prior_scale, shape=(1, n_out))
    
    dot_product = pm.math.dot(x, w)
    linear_combination = pm.math.add(dot_product, b)
    
    return activation(linear_combination)

@pm.model
def model(x, y, prior_scale=1.0):    
    o1 = yield layer('l1', x, n_in=1, n_out=5, prior_scale=prior_scale, activation=pm.math.relu)
    o2 = yield layer('l2', o1, n_in=5, n_out=5, prior_scale=prior_scale, activation=pm.math.relu)
    o3 = yield layer('l3', o2, n_in=5, n_out=1, prior_scale=prior_scale)
    
    yield pm.Normal(name='obs', mu=o3, sigma=noise, observed=y)
```
Changes Made:
1. Replaced tf.tensordot with pm.math.dot.
2. Replaced + b with pm.math.add(dot_product, b).
3. Updated activation functions to use pm.math.relu and similar PyMC functions.

**Comment by twiecki** [comment]
@GarvitDadheech Thanks for taking a look. I don't think this issue is relevant as that guide depends on compatbility between PyMC and TFP, which is not the case anymore. Any particular reason you found this issue?

**Comment by GarvitDadheech** [comment]
> @GarvitDadheech Thanks for taking a look. I don't think this issue is relevant as that guide depends on compatbility between PyMC and TFP, which is not the case anymore. Any particular reason you found this issue?

I was just looking through the open issues and found this one that is still open. There was no particular reason for finding this issue specifically; I just wanted to provide an alternative method. 
Thanks!
