### ISSUE TITLE
Pre-commit getting in the way

### ISSUE THREAD

**Issue by drbenvincent** [pymc-devs/pymc-examples#385]
I’m trying to do an initial commit on my fork of `pymc-examples` so I can do a PR of a new notebook. 

I run the pre-commit checks with `pre-commit run --all`  and it all passes. But then when I try to commit I get errors complaining that the ipynb and myst files are inconsistent. So I delete the myst file and regenerate it by running `pre-commit run --all` again, and I get the same errors. So I’m unable to commit.

Would be great to find a solution to this particular issues, which is just one of a number of specific problems in contributing to the repo.

**Comment by drbenvincent** [comment]
One of the problems I am facing is that the local pre-commit checks are changing the spelling in a URL (which is a not sensible thing to be trying to do). Depending on what way the wind is blowing it seems to only do this on the myst files which then creates a conflict between the ipynb and myst files.

Long story short, the use of `codespell` in the precommit code is causing real issues.

This seems to be introduced by #321 by @hectormz.

Is there a way to get `codespell` to NOT try to fix spelling in URLs? This seems like a very odd thing to be doing in the first place.

If we can't do that, can we just get rid of `codespell` and get people to do this manually? It's making things extremely difficult and is sapping all the fun out of contributing to this repo

**Comment by hectormz** [comment]
@drbenvincent it looks like you have a solution in #388 that might do the trick. I agree, if `codespell` is frustrating or getting in the way, something should be changed.
