### ISSUE TITLE
Add contributing information and link to style guide wiki

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc-examples#42]

**Comment by nibble0101** [comment]
Hi @ricardoV94 
I have applied for outreachy and would love to get used to this project's code base in case my initial application is accepted. Can you kindly guide me?  I can't seem to find contribution or set up instructions for this repository.

**Comment by OriolAbril** [comment]
Hi @nibble0101, thanks for your interest. We recently created this repo and moved the notebooks here from the main pymc3 repo, there are still several resources that are on the main repo only. 

Here is the link to the contributing guide: https://github.com/pymc-devs/pymc3/blob/master/CONTRIBUTING.md and the link to the style guide: https://github.com/pymc-devs/pymc3/wiki/PyMC3-Jupyter-Notebook-Style-Guide

**Comment by OriolAbril** [comment]
I have added a contributing guide with #51
