### ISSUE TITLE
update to cleaner code with `arviz.extract`

### ISSUE THREAD

**Issue by drbenvincent** [pymc-devs/pymc-examples#449]
Lines like this represent a common pattern across many notebooks in the repo:

```python
unpooled_post = unpooled_trace.posterior.stack(chain_draw=("chain", "draw"))
```

This is basically some `xarray` stuff to get a 'flat' vector of MCMC samples by collapsing over chain and draws. But it is arguably unclear, opaque, and potentially frustrating to many users. 

I propose we use the new(ish) [`arviz.extract`](https://python.arviz.org/en/latest/api/generated/arviz.extract.html) function instead. So we would end up with something like this, which is much much clearer to a wide range of pymc users.

```python
unpooled_post = az.extract(unpooled_trace, group='posterior')
```

Tagging @twiecki and @OriolAbril for any thoughts

**Comment by twiecki** [comment]
Yes, way way better.

**Comment by OriolAbril** [comment]
I would only use `group` argument when we want to get variables that are not in the posterior group. We set this default because getting variables from the posterior is the most common operation and it is convenient to skip it
