### ISSUE TITLE
Old version of the notebook GLM-Out-Of-Sample Predictions is currently shown

### ISSUE THREAD

**Issue by juanitorduz** [pymc-devs/pymc-examples#460]
**Notebook title**: GLM in PyMC3: Out-Of-Sample Predictions
**Notebook url**: https://www.pymc.io/projects/examples/en/latest/generalized_linear_models/GLM-out-of-sample-predictions.html

## Issue description
I am the original author of the GLM in PyMC3: Out-Of-Sample Predictions notebook. @drbenvincent  did a fantastic job improving it 🚀 ...but it seems the old (mine initial) version is in the master branch. I believe it was modified in https://github.com/pymc-devs/pymc-examples/pull/376 . It would be great to bring Ben's updated version back!

## Expected output
Lates corrected version which was available before.

## Proposed solution
Maybe revert https://github.com/pymc-devs/pymc-examples/pull/376 ? or simply fix this notebook? My concern is that this could have happened to other notebooks ¯\\_(ツ)_/¯

**Comment by twiecki** [comment]
I think we should remove the NB as it's using the glm submodule.

**Comment by juanitorduz** [comment]
> I think we should remove the NB as it's using the glm submodule.

@drbenvincent did a whole re-write of this notebook, it was great! the problem is that in the PR referenced abve for some reason the new version was replaced by the old one. See the notebook diff  in https://github.com/pymc-devs/pymc-examples/pull/376 ;)

**Comment by drbenvincent** [comment]
So I guess I need to fix this and bring the updated notebook back to life. 

Time wise, could get to that summer point in the festive season when taking a break from my family. If there's urgency then happy if someone else wants to resolve it.
