### ISSUE TITLE
Multilevel modeling

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#47]
file: https://github.com/pymc-devs/pymc-examples/blob/main/examples/case_studies/multilevel_modeling.ipynb

This notebook endured a significant rewrite not too long ago, and is one of the go to examples on ArviZ+xarray usage. This is both its main pro and its own downfall. There are some nits to keep it up to its current golden standard.

## Required changes
The notebook should be reexecuted with latest pymc3 and have the warning filter removed (there should be no warnings, if there are they should be fixed). Moreover, rerunning with latest ArviZ will generate much more aesthetically pleasing forestplots. `legend=True` should be used for forestplots with multiple models.

## Changes for discussion
The plot forest on cell 42 should use the approach described in https://github.com/arviz-devs/arviz/issues/1627 to avoid showing the 1 dots that correspond to the elements in the diagonal.

:warning: These changes need to wait for the next ArviZ release, they require ArviZ>0.11.2, 0.11.2 is not enough.

**Comment by farhanreynaldo** [comment]
Hi @OriolAbril, does this issue also have a time constraint? If not, I would like to work on this issue.

**Comment by OriolAbril** [comment]
This one also has the high impact label, but needs very little changes. Only re executing it with latest pymc and arviz and some cosmetic changes to follow the style guide: https://github.com/pymc-devs/pymc/wiki/PyMC-Jupyter-Notebook-Style-Guide

**Comment by farhanreynaldo** [comment]
Ah sure, may I assign myself on this issue? I will try my best to make the PR as soon as possible.
