### ISSUE TITLE
Bayesian Methods for Reliability Data

### ISSUE THREAD

**Issue by NathanielF** [pymc-devs/pymc-examples#474]
# Notebook proposal
**Bayesian Methods fo reliability Data**

This topic crops up in engineering quite a bit and generally involves a spin on survival analysis  (time to failure) type models, but it's also tightly linked with the notion of cost-benefit, since there is a tolerable degree of failure. I was thinking about riffing on a discussion about prediction intervals for failure analysis in:

https://www.wiley.com/en-us/Statistical+Methods+for+Reliability+Data,+2nd+Edition-p-9781118115459

and contrast the frequentist and Bayesian approach to calibrated prediction. It might be interesting to contrast conformal prediction methods too, since it is a frequentist approach to uncertainty quantification which is getting quite a bit of coverage lately. 

Suggested categories:
* Level: Intermediate
* [Diataxis](https://diataxis.fr/) type: explanation

## Related notebooks
It might have cross over in themes with: https://github.com/pymc-devs/pymc-examples/issues/407
and some of the techniques for modelling the failure predictions draw on survival analysis models.

**Comment by OriolAbril** [comment]
I think it would be a great addition, and it is a great fit for an explanation type notebook (that can/could complement other how-to notebooks on generating predictions for different kind of models for example).

**Comment by NathanielF** [comment]
Did a little work on this over the Christmas holidays. Written up a brief discussion of nonparametric and parametric estimation of reliability distributions and their CDFs. I'm following an example in the book cited above which moves through the frequentist MLE style estimation to a data set with very few failures... it argues for the importance of Bayesian modelling in this case especially.... so I think it's a good example for here.

However, I'm stuck a bit on trying to replicate the model fits achieved in the book or bring them anywhere close to the MLE fits. I'm using a Weibull survival model and I've tried (a) to replicate the stan model they use in the book (b) just use a base pymc  weibull fit adding a potential for lcdf portion of the log likelihood and (c) use the censored model transformation as discussed in one of the survival analysis notebooks by @drbenvincent . I've use both period form and item-period data sets as described in the notebook, but none seem to recover good model fits with the pymc implementation... 

I reckon I must be doing something silly so would appreciate any pointers you might have.

**Comment by NathanielF** [comment]
Think the above discussed issue is resolved now: 
<img width="699" alt="image" src="https://user-images.githubusercontent.com/10588167/210185102-fd20a805-4451-475b-af5e-47e2d62e35a1.png">

<img width="705" alt="image" src="https://user-images.githubusercontent.com/10588167/210185116-621efcab-2e69-48ae-8414-ae03dea3375d.png">

Now just need to write up the contrasting perpsectives on  prediction intervals.

**Comment by NathanielF** [comment]
Ok, i've been banging my head against pre-commit issues on this pull request for a while now. I don't really understand it either since the tests appear to be passing for me locally: 

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/10588167/210669482-68834bfd-87f1-425b-b021-81c5adc73c1e.png">

But when they run in the cloud it breaks on the jupytext test where it says the myst notebook git index is out of date... 

any idea why this might be happening @OriolAbril?

**Comment by NathanielF** [comment]
Some more context on the error. It crashes out with the message here: 

<img width="647" alt="image" src="https://user-images.githubusercontent.com/10588167/210763950-f657ee4d-8937-49d8-81ba-b11a44bcd6cb.png">

But should the paired notebook not appear in the myst nb directory rather than the examples/case_studies directory?

**Comment by NathanielF** [comment]
I suspect the issue has something to do with the metadata like discussed here: https://github.com/mwouts/jupytext/issues/900

My version of jupytext: 

<img width="224" alt="image" src="https://user-images.githubusercontent.com/10588167/210792510-07f0370e-3cce-4319-95b4-5a366e3ae208.png">

Couldn't easily find which version of juyptext the runner is using?

**Comment by NathanielF** [comment]
Ok, fixed the git index issue. Finally realised there was no more msyt notebooks directory on main. But now the docs won't build because it's failing on the watermark extension: 

<img width="939" alt="image" src="https://user-images.githubusercontent.com/10588167/211001190-78d744c3-f9dd-40ec-8c2f-cfbd7b5d8e3d.png">

**Comment by NathanielF** [comment]
Think some of these issues are due to the fact that the Head of the main branch does not reflect the actual latest commit where @drbenvincent has added the template notebook and the myst directory has been removed. 

<img width="604" alt="image" src="https://user-images.githubusercontent.com/10588167/211009647-252c0360-e9bc-4d5a-8403-89e452aa4d8d.png">

**Comment by NathanielF** [comment]
Ok, to summarise my findings so far: 

When i had the old configuration the sphinx docs would build successfully but the pre-commit checks would fail because jupytext expected a note book in the examples/ directory.

The pre-commit checks fail unless there is a myst notebook in the examples/ folder. 
The old jupytext specification added the myst notebook to the myst directory. Changing the jupytext configuration the one visible on github seems to solve the issue of pre-commit checks and populates the notebook in the examples directory.  However, now the sphinx doc build started to fail with the %load extension error. I don't understand why this would be the case but assume it has something to do with the mismatch between commits?

**Comment by OriolAbril** [comment]
Sorry for not seeing this before. Yeah, we recently changed the way pre-commit and jupytext worked because it was often a source of conflicts. It should now be simpler in that running pre-commit will always fix the jupytext step (like black for example), but you have needed to rebase and get rid of the myst_nbs notebook and of the doc build folder (if you built the docs locally).

**Comment by NathanielF** [comment]
All sorted now. Thanks!

**Comment by NathanielF** [comment]
New pull request with passing commit checks is ready for review here:https://github.com/pymc-devs/pymc-examples/pull/491
