### ISSUE TITLE
API Quickstart still imports aesara

### ISSUE THREAD

**Issue by sbenthall** [pymc-devs/pymc-examples#484]
**Notebook title**: API Quickstart
**Notebook url**: https://github.com/pymc-devs/pymc-examples/blob/main/examples/howto/api_quickstart.ipynb

## Issue description

`import aesara.tensor as at`

But `aesara` is no longer installed with `pymc` (at least with `pip`)

## Expected output

No import error.

## Proposed solution

Maybe `import pytensor` etc?

**Comment by twiecki** [comment]
Fixed by https://github.com/pymc-devs/pymc-examples/pull/481.
