### ISSUE TITLE
Sphinx display broken on some Notebooks

### ISSUE THREAD

**Issue by NathanielF** [pymc-devs/pymc-examples#489]
**Multiple Notebooks**:

## Issue description
Pages fail to render properly for certain notebooks on both mobile and desktop:

For example:

![Screenshot_20230103_142536_Chrome](https://user-images.githubusercontent.com/10588167/210377385-034ea738-6cc4-4c4c-8342-a099198cc55a.jpg)

## Expected output
Notebooks should be navigable and show more than just the citation...

**Comment by NathanielF** [comment]
Another example on the GLM Robust notebook: 
![Screenshot_20230103_143418_Chrome](https://user-images.githubusercontent.com/10588167/210378131-67a11bf9-f6a2-4560-8578-514f17617add.jpg)

**Comment by OriolAbril** [comment]
Thanks for reporting, I think I have fixed it. If so please close the issue, if not comment links to the pages that are still broken 🙏🏿

**Comment by NathanielF** [comment]
Looks good now!
