### ISSUE TITLE
BEST

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#52]
File: https://github.com/pymc-devs/pymc-examples/blob/main/examples/case_studies/BEST.ipynb
Reviewers: @twiecki @fonnesbeck

## Known changes needed
Changes listed in this section should all be done at some point in order to get this
notebook to a "Best Practices" state. However, these are probably not enough!
Make sure to thoroughly review the notebook and search for other updates.

### General updates
* Use numpy [Generator](https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator) instead of using the global state random state. Extra reference: https://numpy.org/doc/stable/reference/random/index.html?highlight=random%20sampling%20numpy%20random#quick-start

### Exotic dependencies
None

### Computing requirements
Models sample in less than a minute

**Comment by larryshamalama** [comment]
Submitted a PR [here](https://github.com/pymc-devs/pymc-examples/pull/92)!

**Comment by asuagar** [comment]
Hello @OriolAbril! I would like to try to update this notebook to PyMC 4. I have done BEST before using NumPyro. I have a dumb question about the graphical representation. Can it be used seaborn or other one?

**Comment by OriolAbril** [comment]
Assigned it to you @asuagar, thanks for helping out!

> I have a dumb question about the graphical representation where ArviZ is not used. Can it be used seaborn or other graphical library?

Other libraries can be used for plotting, in many cases ArviZ is not the right tool for the job. i.e. ArviZ is designed to explore bayesian model results, so preliminary exploratory analysis should generally use something else, then use ArviZ afterwards to analyze the posterior. Was that the question?

**Comment by asuagar** [comment]
Yes, it was. It is now clear to me. After reading several notebooks, I thought that there was some kind of limitation to Matplotlib for exploratory data analysis. Thank you by your fast reply.
