### ISSUE TITLE
LKJ

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#53]
File: https://github.com/pymc-devs/pymc-examples/blob/main/examples/case_studies/LKJ.ipynb
Reviewers: @AlexAndorra

## Known changes needed
Changes listed in this section should all be done at some point in order to get this
notebook to a "Best Practices" state. However, these are probably not enough!
Make sure to thoroughly review the notebook and search for other updates.

### ArviZ related
* Use labeled dims in code cells 12 and 13. Also use `.values` instead of `.data`.

## Changes for discussion
Changes listed in this section are up for discussion, these are ideas on how to improve
the notebook but may not have a clear implementation, or fix some know issue only partially.

### ArviZ related
* Show how to index correlation matrixes with xarray. See https://github.com/arviz-devs/arviz/issues/1627 and https://arviz-devs.github.io/arviz/user_guide/label_guide.html#custom-labellers for details and examples on this (note that ArviZ docs are for the development version, at the time of writing, labellers are an unreleased feature)

### Exotic dependencies
None

### Computing power
All models run in less than a minute

**Comment by chiral-carbon** [comment]
taking up this issue.

**Comment by PrinceAsiedu** [comment]
Working on this one

**Comment by twiecki** [comment]
Looks done.
