### ISSUE TITLE
ModelBuilder notebook is missing predicted regression lines

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc-examples#530]
**Using ModelBuilder class for deploying PyMC models**:
**https://www.pymc.io/projects/examples/en/latest/howto/model_builder.html**:

## Issue description
The last plot of the notebook, which is supposed to be predicted regression lines, currently only shows the data points:

![image](https://user-images.githubusercontent.com/81476/225667575-acca476a-8d16-4584-be4b-a807ab6f3690.png)

**Comment by reshamas** [comment]
@BerylKanali is working on this with @Monsurat-Onabajo
