### ISSUE TITLE
example thumbnail gallery rendering broken/wrong

### ISSUE THREAD

**Issue by drbenvincent** [pymc-devs/pymc-examples#537]
The thumbnails appear to have increased in size. This is fantastic. 

But the rendering of this is resulting in only one thumbnail per row.

<img width="1136" alt="Screenshot 2023-03-31 at 09 17 55" src="https://user-images.githubusercontent.com/6765047/229065374-5228580c-a08a-455f-a4f5-c22baf5399df.png">

**Comment by OriolAbril** [comment]
I have no idea what is going on, the theme version is still pinned. I think the best way forward would be to write our own extension again, our current setup is also forcing us to use older versions of sphinx, the theme... as noted in https://github.com/pymc-devs/pymc-examples/issues/409
