### ISSUE TITLE
factor analysis

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#55]
File: https://github.com/pymc-devs/pymc-examples/blob/main/examples/case_studies/factor_analysis.ipynb
Reviewers: ?

## Known changes needed
Changes listed in this section should all be done at some point in order to get this
notebook to a "Best Practices" state. However, these are probably not enough!
Make sure to thoroughly review the notebook and search for other updates.

### General updates
* Use numpy random [Generator](https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator). See also https://numpy.org/doc/stable/reference/random/index.html?highlight=random%20sampling%20numpy%20random#quick-start

### ArviZ related
* Use `return_inferencedata=True`
* Do not use `Deterministic` to "choose" which values to plot, use `coords` when calling the plotting functions
* Consider using dims and coords instead of `shape`
* use xarray and ArviZ for the plot in code cell 7

### Exotic dependencies
None

### Computing requirements
Models seem to take between 1-5 minutes to sample

**Comment by almostmeenal** [comment]
I can take this up, since it seems similar to the previous two notebooks i was/am working on, I'll make a basic draft PR with the changes listed here and whatever else I can notice, after that you can suggest changes. I believe I've been slightly less observant with respect to noticing possible improvements on my own, so I'll work on that.

**Comment by OriolAbril** [comment]
Sounds great, thanks! I expect this one to be much easier than the rugby one, maybe even easier than the sample_stats one (all naming conventions are tricky).

**Comment by ckrapu** [comment]
Sorry for the duplicate effort - I started working on this last night and didn't see the discussion.

**Comment by almostmeenal** [comment]
hi! that's alright, I started working on it half an hour back and I made the numpy changes, I didn't do anything else yet, so maybe push it and I'll make another PR after that adding those?

**Comment by almostmeenal** [comment]
@ckrapu hi! that's alright, I started working on it half an hour back and I made the numpy changes, I didn't do anything else yet, you can take it up, considering the amount of work you've done(just checked the notebook, it looks really good)
just a lil note: I think you missed using rng in for the binomial one and somewhere, just have a look at that maybe.

**Comment by ckrapu** [comment]
Ah, yes. I forgot about the other rv generators. Thanks for the pointer!

**Comment by almostmeenal** [comment]
@OriolAbril considering #98 I'll unassign myself I guess

**Comment by OriolAbril** [comment]
Hi, glad to see the duplicity was kept to a minimum and you both agreed on how to proceed, thanks especially @almostmeenal. 

I just want to note that now with GSoC and especially outreachy (where we have an internship precisely on updating the notebooks in this repo) applications open, more and more people will be working on the repo at the same time, it becomes even more important to follow the guidelines in the [contributing guide](https://github.com/pymc-devs/pymc-examples/blob/main/CONTRIBUTING.md), that in a worst case scenario already [contemplates the possibility of conflicts](https://github.com/pymc-devs/pymc-examples/blob/main/CONTRIBUTING.md#in-the-event-of-a-conflict) and duplicated work, giving preference to the first person to comment in the respective issue. 

That being said, thanks both for all your contributions, you are both doing amazing work with the notebooks you are updating.

**Comment by almostmeenal** [comment]
will keep a note of that!
