### ISSUE TITLE
hierarchical partial pooling

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#56]
File: https://github.com/pymc-devs/pymc-examples/blob/main/examples/case_studies/hierarchical_partial_pooling.ipynb
Reviewers: @OriolAbril

## Changes for discussion
Changes listed in this section are up for discussion, these are ideas on how to improve
the notebook but may not have a clear implementation, or fix some know issue only partially.

### ArviZ related
* Consider using new ArviZ labeling capabilities in the `plot_forest` to avoid having to manually set the yticklabels. We'd instead use coords for that.
   * Note labeller feature in ArviZ has not been released yet, this requires waiting for this.

### Exotic dependencies
None

### Computing power
Model runs in roughly a minute

**Comment by mjhajharia** [comment]
I was working on hierarchical partial pooling last week for a talk proposal!! assigning myself if that's okay

**Comment by OriolAbril** [comment]
That would be great. The only change I had in mind however relies on ArviZ>0.11.2 which I think should be released any day now that gsoc is over? cc @canyon289 was also the release manager here

**Comment by canyon289** [comment]
@mjhajharia Assigning yourself is great. Well probably release arviz before youre done with your talk but thats fine, were going to release it after youre done with your talk too

**Comment by azihna** [comment]
Working on this with @princeasiedu
