### ISSUE TITLE
Correction to mediation analysis notebook for package name

### ISSUE THREAD

**Issue by asarjou** [pymc-devs/pymc-examples#574]
**Notebook title**: mediation_analysis.ipynb
**Notebook url**: https://github.com/pymc-devs/pymc-examples/blob/main/examples/case_studies/mediation_analysis.ipynb

## Issue description
The notebook specifies PYMC3 model when it should specify PYMC model in the markdown cell. 

*Note that this issue tracker is about the contents in the notebooks, if
the notebook is instead triggering a bug or error in pymc, please
report to https://github.com/pymc-devs/pymc/issues instead*

## Expected output
Should say: "Define the PyMC3 model and conduct inference"

## Proposed solution
Adjustment to Markdown in the notebook

**Comment by OriolAbril** [comment]
Thanks for reporting!
