### ISSUE TITLE
Update Factor analysis notebook

### ISSUE THREAD

**Issue by erik-werner** [pymc-devs/pymc-examples#587]
**Factor analysis**:
**https://www.pymc.io/projects/examples/en/latest/case_studies/factor_analysis.html**:

## Issue description
I think there's a small error in one of the equations at the end of the notebook. There's a missing $\Psi^{-1/2}$ in the last equation, the RHS should read $\Psi^{-1/2}N(F, (W^TW)^{-1})$. I think this error carries over to the sampling code.
But there are quite a few unexplained steps in the derivation, so it's not obvious to me what is done, nor how it relates to the code.

Further, since the notebook uses synthetic data, it would be nice to end the notebook with a comparison between the true latent factors and the estimates from the factor analysis.

Todo:
- Spell out the steps in the mathematical derivation
- Fix any errors
- Make the connection between the equations and the code clearer
- Add a section at the end to compare the latent factors that we've identified with the true ones from the synthetic data.

**Comment by drbenvincent** [comment]
Hi @erik-werner. Did #586 address this issue? If so we can close this issue :)

**Comment by erik-werner** [comment]
Hi @drbenvincent. No. I"m working on some updates to address this issue, but got sidelined by some other stuff. I'm hoping to be able to pick it up later this week.
