### ISSUE TITLE
Change category items for beginner, intermediate, advanced from birds to text

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc-examples#607]
Currently there are three birds which users fails to understand the meaning of:
<img width="252" alt="image" src="https://github.com/pymc-devs/pymc-examples/assets/674200/c4f57fd7-2700-4bbf-868a-cb9e196f548b">

Would be better to change to text. However, looking at the code: https://github.com/pymc-devs/pymc-examples/blob/main/_templates/postcard_categories.html#L38 I couldn't figure out how to change it the correct way. @OriolAbril do you know?

**Comment by OriolAbril** [comment]
The file that needs to be modified is that one. But I don't think the three levels will fit side by side. I think there are two main options: putting each in their own line, or using `Level: 1 2 3` in the same line so the look is a bit more similar.

Note that categories are fixed, there can only be these 7 (anything else will be ignored) and they are all always present, with the categories of the page being browsed (in case it has any categories) are highlighted in green.

**Comment by drbenvincent** [comment]
An alternative would be to remove the level of difficulty altogether. I don't have a strong opinion about that, but I agree with @twiecki's point that the meaning of the icons is not immediately obvious.
