### ISSUE TITLE
Propensity Score Non-Parametric Models

### ISSUE THREAD

**Issue by NathanielF** [pymc-devs/pymc-examples#623]
# Notebook proposal
**Propensity Score Non-Parametric Models**

## Why should this notebook be added to pymc-examples?
There is a widely used approach to causal inference using propensity scores to reweight the and create psuedo populations under which causal inference is licensed. State of the art approaches to estimating propensity scores can use non-parametric methods such as BART to capture heterogenous effects. 

Suggested categories:
* Level: Intermediate
* [Diataxis](https://diataxis.fr/) type:

## Related notebooks
We reference the work done in https://www.pymc.io/projects/examples/en/latest/bart/bart_quantile_regression.html
to infer causal effects at the higher quantiles of the distribution

# References
Osvaldo A Martin, Ravin Kumar, and Junpeng Lao. Bayesian Modeling and Computation in Python. Chapman and Hall/CRC, 2021.

https://www.amazon.co.uk/Nonparametrics-Inference-Monographs-Statistics-Probability/dp/036734100X/ref=asc_df_036734100X/?tag=googshopuk-21&linkCode=df0&hvadid=659098793966&hvpos=&hvnetw=g&hvrand=12876422308331539704&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1007850&hvtargid=pla-2035474796142&psc=1&mcid=8d6c3651ff9c3dd0aa26ec01a735e4d8

https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/

cc @drbenvincent  and @aloctavodia 

This is still a work in progress,  but something i started playing with over the Christmas break

**Comment by drbenvincent** [comment]
Sounds pretty cool. This reminds me that I've got a _very_ early sketch of a notebook on propensity scores. It's not even a draft PR at this point, but here's a link to the branch on my fork if you were interested https://github.com/drbenvincent/pymc-examples/blob/propensity/examples/causal_inference/propensity_scores.ipynb

I don't see any meaningful overlap or conflict between the two notebooks if I were to pick up mine in the future.
