### ISSUE TITLE
Notebook Proposal : Time Series Modeling with HSGP: Baby Births Example

### ISSUE THREAD

**Issue by juanitorduz** [pymc-devs/pymc-examples#626]
# Notebook proposal
**Title**: Time Series Modeling with HSGP: Baby Births Example

## Why should this notebook be added to pymc-examples?
I recently published a blog post of this model [Time Series Modeling with HSGP: Baby Births Example](https://juanitorduz.github.io/birthdays/) based on the great post https://avehtari.github.io/casestudies/Birthdays/birthdays.html by [Aki Vehtari](https://users.aalto.fi/~ave/). I got good feedback and when talking with @bwengals , we believe it could be a nice addition to the example gallery.

**Scope:** My original post is very *verbose* as it was essentially written for myself as a future reference. Hence, we can have a condensed version. I also suggest we implement a simpler model as we want users to get an example of HSGP in the periodic and not periodic cases. Therefore, we can have a long-term trend GP, a periodic yearly GP and a `ZeroSumNormal` for the weekday seasonality. This is already a good baseline and we can add references for more complex models. 

Suggested categories:
* Level: Intermediate
* [Diataxis](https://diataxis.fr/) type: How-to-guide

## Related notebooks
[Time Series Modeling with HSGP: Baby Births Example](https://juanitorduz.github.io/birthdays/) 

# References
https://avehtari.github.io/casestudies/Birthdays/birthdays.html by [Aki Vehtari](https://users.aalto.fi/~ave/)

**Comment by juanitorduz** [comment]
After very insightful discussions with @bwengals, we believe this notebook can have more ambitious objectives: 

1. Reference for how to use HSGP
2. Case study which illustrates some of the issues that come up with HSGPs.  This Birthdays example is a great vehicle for that. 
3. Illustrate Bayesian workflow, eda -> model building, and how to make a good model for a particularly complex data set.

This notebook will probably be a long one so we suggest working on self-contained iterations, i.e. after each point above is completed and passes all the requirements (pre-commit, typos, ...) we merge and continue with the next point in a different PR. 

Any thoughts?

**Comment by AlexAndorra** [comment]
Great idea @juanitorduz ! That will also make our reviewing job easier ;)
