### ISSUE TITLE
Do operator example still mentions PyMC-Experimental

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc-examples#633]
Do stuff is now in PyMC

https://www.pymc.io/projects/docs/en/stable/api/model/generated/pymc.model.transform.conditioning.do.html

**Comment by HarshvirSandhu** [comment]
I would like to work on this issue

**Comment by ricardoV94** [comment]
That would be great!

**Comment by juanitorduz** [comment]
I guess we can close this one @ricardoV94 ?

**Comment by ricardoV94** [comment]
Thanks for the reminder @juanitorduz
