### ISSUE TITLE
Math rendering issue in golf putting example

### ISSUE THREAD

**Issue by isms** [pymc-devs/pymc-examples#657]
**Notebook title**: Model building and expansion for golf putting
**Notebook url**: https://github.com/pymc-devs/pymc-examples/blob/main/examples/case_studies/putting_workflow.ipynb

## Issue description
Small LaTeX issue ( `$$` blocks) results in bad render which looks fine in the Jupyter notebook while working on it but not in the rendered result.

### Rendered by sphinx
![image](https://github.com/pymc-devs/pymc-examples/assets/1284973/4069e656-c743-4e6d-9ccf-54da04cae0f7)

### Code in notebook
```
3. The distance the ball goes, $u$, is distributed according to
$$
u \sim \mathcal{N}\left(1 + \text{distance}, \sigma_{\text{distance}} (1 + \text{distance})\right),
$$
where we will learn $\sigma_{\text{distance}}$.

Again, this is a geometry and algebra problem to work the probability that the ball goes in from any given distance:
$$
P(\text{good distance}) = P(\text{distance} < u < \text{distance} + 3)
$$
```

### Expected output (as rendered properly while in Jupyter notebook)

![image](https://github.com/pymc-devs/pymc-examples/assets/1284973/901b2b8f-5efe-4af5-b7d4-84a0fe459ed5)

## Proposed solution
Fix `$$` enclosures either inline or in the sphinx rendering pipeline

**Comment by ricardoV94** [comment]
@isms do you want to open a PR to fix it?

**Comment by isms** [comment]
@ricardoV94 Working on it now -- trying to assess whether it's specific to this notebook (for example, as a result of being in a numbered list) or a configuration issue that affects all `$$` blocks across notebooks.

**Comment by isms** [comment]
Looks like it affects all of them, e.g. in the rugby analytics case study, this

```
$$log \\theta_{g1} = home + att_{h(g)} + def_{a(g)} $$
$$log \\theta_{g2} = att_{a(g)} + def_{h(g)}$$
```

Renders as this:
![image](https://github.com/pymc-devs/pymc-examples/assets/1284973/5160c932-474b-4985-b9f9-6646f94c9ea5)

**Comment by isms** [comment]
Looks like it only happens when the `$$` block is inline (no leading newlines), and is related to this issue: https://github.com/executablebooks/jupyter-book/issues/1181
