### ISSUE TITLE
Update data container notebook to reflect changes to `pm.Data`

### ISSUE THREAD

**Issue by jessegrabowski** [pymc-devs/pymc-examples#659]
https://github.com/pymc-devs/pymc/pull/7047 depreciates `pm.ConstantData` and `pm.MutableData` (again), so the [data container notebook](https://www.pymc.io/projects/examples/en/latest/fundamentals/data_container.html) no longer reflects best practices. It should be updated to:

1. Remove the explainer about the differences between `MutableData` and `ConstantData`, since it no longer exists, and;
2. Use `pm.Data` everywhere in the applied examples

**Comment by Dekermanjian** [comment]
Hey, would it be alright if I worked on this?
