### ISSUE TITLE
Broken link in Weibull Accelerated Failure Time Model notebook

### ISSUE THREAD

**Issue by cluhmann** [pymc-devs/pymc-examples#661]
**Notebook title**: Reparameterizing the Weibull Accelerated Failure Time Model
**Notebook url**: https://www.pymc.io/projects/examples/en/latest/survival_analysis/weibull_aft.html

## Issue description
Opening paragraph begins:
> Dataset
> The [previous example notebook on Bayesian parametric survival analysis](https://docs.pymc.io/notebooks/bayes_param_survival.html) introduced two different accelerated failure time (AFT) models: Weibull and log-linear. In this notebook, we present three different parameterizations of the Weibull AFT model.

But the link to the "previous example notebook on Bayesian parametric survival analysis" is broken.  It points [here](https://docs.pymc.io/notebooks/bayes_param_survival.html) currently.  Not sure where it's supposed to point. Possibly [here](https://www.pymc.io/projects/examples/en/latest/survival_analysis/bayes_param_survival_pymc3.html) (which is massively out of date)?

**Comment by pradyutf** [comment]
Hi, @cluhmann 

I'd like to work on this issue. From what I understand, I need to change the link to the one suggested in the issue description. Please let me know if there are any other updated links or additional changes required.

Could you please assign this issue to me?
Thank you!
