### ISSUE TITLE
GP Kron

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#71]
File: https://github.com/pymc-devs/pymc-examples/blob/main/examples/gaussian_processes/GP-Kron.ipynb
Reviewers:

> The sections below may still be pending. If so, the issue is still available, it simply doesn't
> have specific guidance yet. Please refer to [this overview of updates](https://github.com/pymc-devs/pymc-examples/wiki/Notebook-updates-overview)

## Known changes needed
Changes listed in this section should all be done at some point in order to get this
notebook to a "Best Practices" state. However, these are probably not enough!
Make sure to thoroughly review the notebook and search for other updates.

### General updates
*

### ArviZ related
*

## Changes for discussion
Changes listed in this section are up for discussion, these are ideas on how to improve
the notebook but may not have a clear implementation, or fix some know issue only partially.

### General updates
*

### ArviZ related
*

**Comment by ckrapu** [comment]
I'd like to work on updating this one. I think it could be expanded with a space-time example using the Kronecker GP.

**Comment by OriolAbril** [comment]
That would be amazing, thanks! I'll do my best to review, but I am not sure I'll be able to offer much on GPs

**Comment by OriolAbril** [comment]
Still needs some ArviZ related updates roughly listed on #144
