### ISSUE TITLE
GLM hierarchical

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#80]
File: https://github.com/pymc-devs/pymc-examples/blob/main/examples/generalized_linear_models/GLM-hierarchical.ipynb
Reviewers: @twiecki 

> The sections below may still be pending. If so, the issue is still available, it simply doesn't have specific guidance yet. Please refer to [this overview of updates](https://github.com/pymc-devs/pymc-examples/wiki/Notebook-updates-overview)

## Known changes needed
Changes listed in this section should all be done at some point in order to get this
notebook to a "Best Practices" state. However, these are probably not enough!
Make sure to thoroughly review the notebook and search for other updates.

### General updates
* use try except in data reading
* Add code for rmse mentioned in the notebook, see https://discourse.pymc.io/t/glm-hierarchical-linear-regression-posterior-predictive-check-rmsd/5668

### ArviZ related
* use return_inferencedata=True
* update slope plotting code
   * use idata and xarray. :warning: first operate, then average, the sum of averages is not necessarily the average of the sum.
   * be careful with zorder, alpha and linestyles, markers... to ensure the plot is easy to read for everyone and conveys the relevant information.

## Changes for discussion
Changes listed in this section are up for discussion, these are ideas on how to improve
the notebook but may not have a clear implementation, or fix some know issue only partially.

### General updates

* This references the multilevel modeling notebook both as general document and specific cells! :warning: with hardcoded links and cell numbers. We should define anchors back in multilevel modeling and use those anchors here. This may be possible in nbsphinx, but I'd say this is a motive to move to myst-nb where it's natural to use rst directives from markdown.

### Exotic dependencies
None

**Comment by chiral-carbon** [comment]
Hi! I would like to take up this issue.

**Comment by OriolAbril** [comment]
Sorry about the bad tracking in this case @chiral-carbon, there was already a PR open for that but it wasn't properly linked, you can help reviewing the PR if you are interested in this specific notebook, the more eyes the better :smile:

**Comment by chiral-carbon** [comment]
oh okay, no worries!

**Comment by reshamas** [comment]
I will work on this notebook.

**Comment by OriolAbril** [comment]
This notebook has been deleted and superseeded by https://www.pymc.io/projects/examples/en/latest/case_studies/multilevel_modeling.html
