### ISSUE TITLE
GLM logistic

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#82]
File: https://github.com/pymc-devs/pymc-examples/blob/main/examples/generalized_linear_models/GLM-logistic.ipynb
Reviewers:

> The sections below may still be pending. If so, the issue is still available, it simply doesn't
> have specific guidance yet. Please refer to [this overview of updates](https://github.com/pymc-devs/pymc-examples/wiki/Notebook-updates-overview)

## Known changes needed
Changes listed in this section should all be done at some point in order to get this
notebook to a "Best Practices" state. However, these are probably not enough!
Make sure to thoroughly review the notebook and search for other updates.

### General updates
*

### ArviZ related
*

## Changes for discussion
Changes listed in this section are up for discussion, these are ideas on how to improve
the notebook but may not have a clear implementation, or fix some know issue only partially.

### General updates
*

### ArviZ related
*

**Comment by twiecki** [comment]
This is also using the deprecated `glm` submodule which we should remove and implement a logistic regression directly.

**Comment by chiral-carbon** [comment]
hey! can I take this up?

**Comment by twiecki** [comment]
Totally, thanks for offering to help.

**Comment by drbenvincent** [comment]
I can update this to v4

**Comment by drbenvincent** [comment]
@OriolAbril / @twiecki 
I've started to port this, but noticed that it overlaps _a lot_ with an official Bambi example (see https://bambinos.github.io/bambi/main/notebooks/model_comparison.html)

I will definitely link to that, but I'm wondering if this notebook is essentially redundant?

Let me know if we should kill this or just continue to port what is there.

**Comment by cfonnesbeck** [comment]
I vote in favor of removing. We should take advantage of any opportunity to reduce the size of the example library.

**Comment by aloctavodia** [comment]
Agreed. Is there a place in PyMC were we redirect/point to bambi for GLMs?

**Comment by drbenvincent** [comment]
Ok. Will submit PR to remove this

> Agreed. Is there a place in PyMC were we redirect/point to bambi for GLMs?

Some of the GLM notebooks do hand coded PyMC models. Some include Bambi only. Some contain a mix.

If we were going to move towards being consistent, my preference would be to focus on hand coded PyMC models but with linking to Bambi and possibly including non-executed Bambi code in markdown cells.

Why? I think it makes sense to avoid creating a dependency upon the Bambi API. If it changes then we have to update the PyMC examples. This also then creates redundancy. It also goes against the whole 'lego block' approach of building your own models with PyMC.

I think Bambi is fantastic, but for the PyMC examples, my feeling is that we should avoid Bambi only notebooks. 

But in the mean time I'll open a PR to remove this notebook.

**Comment by twiecki** [comment]
Closed via #345.

**Comment by aloctavodia** [comment]
Totally agree about focusing on hand coded model here even more we could  have the handcoded version here and the formula version in bambi doc and mutually crossrefrence notebooks.
