### ISSUE TITLE
GLM negative binomial

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#84]
File: https://github.com/pymc-devs/pymc-examples/blob/main/examples/generalized_linear_models/GLM-negative-binomial-regression.ipynb
Reviewers:

> The sections below may still be pending. If so, the issue is still available, it simply doesn't
> have specific guidance yet. Please refer to [this overview of updates](https://github.com/pymc-devs/pymc-examples/wiki/Notebook-updates-overview)

## Known changes needed
Changes listed in this section should all be done at some point in order to get this
notebook to a "Best Practices" state. However, these are probably not enough!
Make sure to thoroughly review the notebook and search for other updates.

### General updates
* Add cross reference where it mentions another notebook "First, let's look at some Poisson distributed data from the Poisson regression example."

### ArviZ related
*

## Changes for discussion
Changes listed in this section are up for discussion, these are ideas on how to improve
the notebook but may not have a clear implementation, or fix some know issue only partially.

### General updates
*

### ArviZ related
*

**Comment by chiral-carbon** [comment]
Hi! I was thinking of taking this notebook up next! should I go ahead and assign myself?

**Comment by OriolAbril** [comment]
Yes, feel free to self assign to unclaimed issues :)
