### ISSUE TITLE
GLM robust

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#88]
File: https://github.com/pymc-devs/pymc-examples/blob/main/examples/generalized_linear_models/GLM-robust.ipynb
Reviewers:

> The sections below may still be pending. If so, the issue is still available, it simply doesn't
> have specific guidance yet. Please refer to [this overview of updates](https://github.com/pymc-devs/pymc-examples/wiki/Notebook-updates-overview)

## Known changes needed
Changes listed in this section should all be done at some point in order to get this
notebook to a "Best Practices" state. However, these are probably not enough!
Make sure to thoroughly review the notebook and search for other updates.

### General updates
*

### ArviZ related
*

## Changes for discussion
Changes listed in this section are up for discussion, these are ideas on how to improve
the notebook but may not have a clear implementation, or fix some know issue only partially.

### General updates
*

### ArviZ related
*

**Comment by chiral-carbon** [comment]
Hi! I'm taking this issue up.

**Comment by OriolAbril** [comment]
Needs changing `pm.plot_posterior_predictive_glm` to `az.plot_lm` once next ArviZ version is released

**Comment by kuvychko** [comment]
I'd like to take this issue

**Comment by reshamas** [comment]
@kuvychko Are you still working on this notebook for GLM robust?

**Comment by kuvychko** [comment]
@reshamas - yes, I apologize for being slow, life got in the way. I will have it done by end of next week, if that's ok.

**Comment by reshamas** [comment]
> @reshamas - yes, I apologize for being slow, life got in the way. I will have it done by end of next week, if that's ok.

@kuvychko thanks for the quick response.  It's no rush. I was taking inventory of what notebooks still needed to be done.
