### ISSUE TITLE
GLM truncated & censored

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#90]
File: https://github.com/pymc-devs/pymc-examples/blob/main/examples/generalized_linear_models/GLM-truncated-censored-regression.ipynb
Reviewers:

> The sections below may still be pending. If so, the issue is still available, it simply doesn't
> have specific guidance yet. Please refer to [this overview of updates](https://github.com/pymc-devs/pymc-examples/wiki/Notebook-updates-overview)

## Known changes needed
Changes listed in this section should all be done at some point in order to get this
notebook to a "Best Practices" state. However, these are probably not enough!
Make sure to thoroughly review the notebook and search for other updates.

### General updates
*

### ArviZ related
*

## Changes for discussion
Changes listed in this section are up for discussion, these are ideas on how to improve
the notebook but may not have a clear implementation, or fix some know issue only partially.

### General updates
*

### ArviZ related
*

**Comment by drbenvincent** [comment]
I had this example notebook accepted a few months ago - never made it live on the website. I think it just needs some small things done (i.e. from the [Notebook updates overview](https://github.com/pymc-devs/pymc-examples/wiki/Notebook-updates-overview)) to follow best practice. Happy for you to assign me to this.

**Comment by drbenvincent** [comment]
Just checking the procedure... I should make a pull request when I'm done, and reference this issue?

**Comment by OriolAbril** [comment]
Yes, when you open the PR link this issue so it will keep track of all the evolution of the notebook. Once merged I'll triage it to "best practices" and github will add the "oriol moved this issue to best practices in notebook tracker", then someone will make a PR for v4 also linkong here...

**Comment by chiral-carbon** [comment]
can I take this up?

**Comment by drbenvincent** [comment]
This is now done here in a notebook that has been merged https://github.com/pymc-devs/pymc-examples/blob/main/examples/generalized_linear_models/GLM-truncated-censored-regression.ipynb
 I think we can close this issue now?

**Comment by OriolAbril** [comment]
Please do not close any `tracker id` issue yet :pray: , I created an issue per notebook and try to keep them up to date so we can easily see where we stand by looking at https://github.com/pymc-devs/pymc-examples/projects/1. I described this approach in the [contributing guide](https://github.com/pymc-devs/pymc-examples/blob/main/CONTRIBUTING.md#about-the-notebook-tracker-project). We can start closing issues after the notebook has been updated and reexecuted with v4 instead of waiting for all notebook to use v4, but for now I want the issue as a remainder that this still needs to be reexecuted with v4 to make sure it runs and be updated to work with it if needed.

I also make sure all PRs link to the right issue, so if everithing goes according to plan and I don't forget anything, the issues themselves will (like this one) show the "xxx mentioned this issue" with the merged icon and label as well as the "xxx added this to Column # in Notebook state tracker", which I think is informative enough for people who want to work on this to see what needs to be done about the issue.
