### ISSUE TITLE
dependent density regression

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#99]
File: https://github.com/pymc-devs/pymc-examples/blob/main/examples/mixture_models/dependent_density_regression.ipynb
Reviewers:

> The sections below may still be pending. If so, the issue is still available, it simply doesn't
> have specific guidance yet. Please refer to [this overview of updates](https://github.com/pymc-devs/pymc-examples/wiki/Notebook-updates-overview)

## Known changes needed
Changes listed in this section should all be done at some point in order to get this
notebook to a "Best Practices" state. However, these are probably not enough!
Make sure to thoroughly review the notebook and search for other updates.

### General updates
*

### ArviZ related
*

## Changes for discussion
Changes listed in this section are up for discussion, these are ideas on how to improve
the notebook but may not have a clear implementation, or fix some know issue only partially.

### General updates
*

### ArviZ related
*

**Comment by chiral-carbon** [comment]
this notebook is updated except for a minor thing in the beginning where it does not use `numpy Generator` instead of `numpy.random`. can I open a PR for this?

**Comment by OriolAbril** [comment]
It should also add the posterior predictive samples to the InferenceData and update the plotting in the last cell. `low, high = np.percentile(pp_trace["obs"], [2.5, 97.5], axis=0)` for example could use xarray and specify which dimensions are reduced explicitly.

Note that unlike most notebooks, this one is not uncategorized within the notebook tracker project but it's triaged to the "to do" indicating that both changes related to arviz and to general updates are needed
